"use client";

import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent, type ReactNode } from "react";
import Link from "next/link";
import { motion } from "motion/react";
import { ArrowDown, ArrowUpRight, Briefcase, Code, GithubLogo, LinkedinLogo, List, Moon, PaperPlaneTilt, Sparkle, Sun, X } from "@phosphor-icons/react";

type Theme = "light" | "dark";
type Contribution = { date: string; count: number; level: 0 | 1 | 2 | 3 | 4 };

const projects = [
  ["01", "House Price Prediction", "Regression", "Predicting house prices with Python and a practical ML workflow.", ["Python", "pandas", "NumPy", "scikit learn"], "https://housepriceprediction-rqo8ykwgldxbpemwl6kvok.streamlit.app/", "https://github.com/SohailKhan0525/HousePricePrediction"],
  ["02", "Global Earthquake Prediction", "Classification", "An applied classification project exploring earthquake prediction.", ["Python", "pandas", "NumPy", "scikit learn"], "https://github.com/SohailKhan0525/Global-Earthquake-Prediction", "https://github.com/SohailKhan0525/Global-Earthquake-Prediction"],
  ["03", "Heart Disease Prediction", "Logistic regression", "A Streamlit app turning a classification model into an interactive experience.", ["Python", "scikit learn", "Streamlit"], "https://heartdiseaseml-4zrcurmudxpfxbwygcuyytm.streamlit.app/", "https://github.com/SohailKhan0525/HeartDiseaseML"],
  ["04", "Student Management", "Python app", "A practical student management application with a hosted interface.", ["Python", "Streamlit"], "https://studentmanagementproject-ulj54ytmcyj55upzakbzhn.streamlit.app/", "https://github.com/SohailKhan0525/StudentManagementProject"],
  ["05", "Student Pass / Fail Predictor", "Classification", "A small interactive application for predicting student outcomes.", ["Python", "scikit learn", "Streamlit"], "https://studentfailpasspredictor-hjymwbpsp4bksec9ycb2xz.streamlit.app/", "https://github.com/SohailKhan0525/StudentFailPassPredictor"],
  ["06", "Bank Management", "Python app", "A practical project focused on application logic and Python fundamentals.", ["Python", "Streamlit"], "https://bankmanagementproject-brt9pt282uavy8ddzzy7ql.streamlit.app/", "https://github.com/SohailKhan0525/BankManagementProject"],
  ["07", "File Handling", "Python CLI", "A focused project for everyday file operations and application code.", ["Python", "OOP", "pathlib", "JSON"], "https://github.com/SohailKhan0525/File_Handling_Project", "https://github.com/SohailKhan0525/File_Handling_Project"],
] as const;

const skills = [["Python", "Primary language"], ["scikit learn", "ML workflows"], ["pandas", "Data analysis"], ["NumPy", "Numerical computing"], ["Streamlit", "Interactive apps"], ["Git / GitHub", "Version control"], ["HTML / CSS / JS", "Web foundations"]];

function tone(kind: "tap" | "success") {
  if (typeof window === "undefined" || localStorage.getItem("portfolio-sound") === "off") return;
  try {
    const Ctor = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!Ctor) return;
    const ctx = new Ctor({ latencyHint: "interactive" });
    const osc = ctx.createOscillator(); const gain = ctx.createGain(); const now = ctx.currentTime;
    osc.type = "sine"; osc.frequency.setValueAtTime(kind === "success" ? 440 : 320, now); osc.frequency.exponentialRampToValueAtTime(kind === "success" ? 660 : 240, now + .06);
    gain.gain.setValueAtTime(.0001, now); gain.gain.exponentialRampToValueAtTime(kind === "success" ? .025 : .014, now + .006); gain.gain.exponentialRampToValueAtTime(.0001, now + .075);
    osc.connect(gain).connect(ctx.destination); osc.start(now); osc.stop(now + .08); osc.addEventListener("ended", () => void ctx.close());
  } catch {}
}

function useTheme() {
  const [theme, setTheme] = useState<Theme>("dark");
  useEffect(() => { const saved = localStorage.getItem("portfolio-theme"); const next: Theme = saved === "light" || saved === "dark" ? saved : "dark"; setTheme(next); document.documentElement.dataset.theme = next; }, []);
  const change = (next: Theme) => { localStorage.setItem("portfolio-theme", next); setTheme(next); document.documentElement.dataset.theme = next; tone("success"); };
  return { theme, change };
}

function Reveal({ children, delay = 0, className = "" }: { children: ReactNode; delay?: number; className?: string }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .65, delay, ease: [.32, .72, 0, 1] }}>{children}</motion.div>;
}

function ThemeToggle({ theme, change }: { theme: Theme; change: (theme: Theme) => void }) {
  const next = theme === "dark" ? "light" : "dark";
  return <button className="icon-button theme-button" type="button" aria-label={`Switch to ${next} mode`} title={`Switch to ${next} mode`} onClick={() => change(next)}>{theme === "dark" ? <Sun size={18} weight="bold" aria-hidden="true"/> : <Moon size={18} weight="bold" aria-hidden="true"/>}</button>;
}

function Contributions() {
  const [days, setDays] = useState<Contribution[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true);
  useEffect(() => { let alive = true; fetch("https://github-contributions-api.jogruber.de/v4/SohailKhan0525?y=last", { cache: "no-store" }).then(r => r.ok ? r.json() : Promise.reject()).then(data => { if (!alive) return; const items = Array.isArray(data.contributions) ? data.contributions as Contribution[] : []; setDays(items); setTotal(Number(data.total?.lastYear ?? items.reduce((s, d) => s + d.count, 0))); }).catch(() => {}).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, []);
  const active = days.filter(d => d.count > 0).length;
  const streak = useMemo(() => { let n = 0; for (const d of [...days].sort((a,b) => b.date.localeCompare(a.date))) { if (d.count) n++; else if (n) break; } return n; }, [days]);
  return <div className="surface activity-card"><div className="activity-head"><div><p className="eyebrow">GitHub activity</p><h3>{loading ? "Loading activity…" : `${total} contributions`}</h3><p>Public contribution activity from the last 12 months.</p></div><a className="button button-secondary" href="https://github.com/SohailKhan0525" target="_blank" rel="noreferrer"><GithubLogo size={17}/> GitHub <ArrowUpRight size={15}/></a></div><div className="activity-stats"><div><strong>{total}</strong><span>Contributions</span></div><div><strong>{active}</strong><span>Active days</span></div><div><strong>{streak}</strong><span>Current streak</span></div></div><div className="contribution-grid" aria-label="GitHub contribution activity">{days.slice(-182).map(day => <span key={day.date} className={`level-${day.level}`} title={`${day.count} contributions · ${day.date}`}/>)}</div><div className="activity-legend"><span>Less</span>{[0,1,2,3,4].map(level => <i key={level} className={`level-${level}`}/>)}<span>More</span></div></div>;
}

function Terminal() {
  const commands = ["help", "about", "projects", "skills", "contact", "clear"]; const [input, setInput] = useState(""); const [history, setHistory] = useState<string[]>([]); const [index, setIndex] = useState(-1); const [ready, setReady] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { const t = setTimeout(() => setReady(true), 400); return () => clearTimeout(t); }, []);
  const output = (cmd: string) => cmd === "help" ? ["help      show commands", "about     current focus", "projects  selected work", "skills    current toolkit", "contact   jump to contact", "clear     clear terminal"] : cmd === "about" || cmd === "whoami" ? ["Mohd Zaheer Uddin", "CSIT undergraduate · ML & Data Science", "building practical Python + ML projects."] : cmd === "projects" || cmd === "ls" ? projects.map(p => `${p[0]}  ${p[1]}`) : cmd === "skills" ? ["Python · scikit learn · pandas · NumPy", "Streamlit · Git/GitHub · HTML/CSS/JS"] : cmd === "contact" ? ["Opening contact section…"] : [`command not found: ${cmd}`, `type "help" to see available commands`];
  const submit = (e: FormEvent) => { e.preventDefault(); const cmd = input.trim().toLowerCase(); if (!cmd) return; if (cmd === "clear") { setHistory([]); setInput(""); tone("tap"); return; } setHistory(h => [...h, `$ ${input}`, ...output(cmd)]); setInput(""); setIndex(-1); if (cmd === "contact") setTimeout(() => document.querySelector("#contact")?.scrollIntoView({ behavior: "smooth" }), 80); tone("success"); };
  const key = (e: KeyboardEvent<HTMLInputElement>) => { const items = history.filter(x => x.startsWith("$ ")).map(x => x.slice(2)); if (e.key === "Tab") { e.preventDefault(); const match = commands.find(c => c.startsWith(input.toLowerCase())); if (match) setInput(match); } if (e.key === "ArrowUp") { e.preventDefault(); if (!items.length) return; const n = Math.min(index + 1, items.length - 1); setIndex(n); setInput(items[items.length - 1 - n] ?? ""); } if (e.key === "ArrowDown") { e.preventDefault(); if (index <= 0) { setIndex(-1); setInput(""); } else { const n = index - 1; setIndex(n); setInput(items[items.length - 1 - n] ?? ""); } } };
  return <div className="hero-terminal-real" onClick={() => inputRef.current?.focus()}><div className="terminal-top"><div className="terminal-top-left"><span className="terminal-dots"><i/><i/><i/></span><span className="terminal-tab">portfolio.py</span><span className="terminal-title">zsh — portfolio</span></div><span className="terminal-status"><i/> ready</span></div><div className="terminal-screen"><div className="terminal-boot"><b>portfolio@zaheer</b>:~$ ./start.sh<br/><span>{ready ? "profile loaded · terminal ready." : "initializing…"}</span></div><div className="terminal-history" aria-live="polite">{history.slice(-12).map((line,i) => <div key={`${line}-${i}`} className={`terminal-line ${line.startsWith("$ ") ? "terminal-command" : "terminal-output-line"}`}>{line}</div>)}</div><form className="terminal-form" onSubmit={submit}><span className="terminal-prompt">$</span><input ref={inputRef} className="terminal-input" value={input} onChange={e => setInput(e.target.value)} onKeyDown={key} disabled={!ready} placeholder={ready ? "type a command…" : "initializing…"} aria-label="Terminal command" autoComplete="off" spellCheck={false}/></form><div className="terminal-help"><span>↑↓ history · Tab autocomplete · Enter run</span><div className="terminal-quick">{["help","projects","skills","about"].map(cmd => <button key={cmd} type="button" className="terminal-chip" onClick={() => { setInput(cmd); inputRef.current?.focus(); }}>{cmd}</button>)}</div></div></div><div className="terminal-bottom"><span>PORTFOLIO SHELL v1.0</span><span>interactive · responsive</span></div></div>;
}

export default function Home() {
  const { theme, change } = useTheme(); const [mobile, setMobile] = useState(false); const [active, setActive] = useState(0); const [copied, setCopied] = useState(false); const email = "sohailkhannnn.0525@gmail.com";
  const copyEmail = async () => { try { await navigator.clipboard.writeText(email); setCopied(true); tone("success"); setTimeout(() => setCopied(false), 1500); } catch { window.location.href = `mailto:${email}`; } };
  const nav = [["Work","#work"],["About","#about"],["Journey","#journey"],["Skills","#skills"],["Resume","/resume"],["Contact","#contact"]]; const project = projects[active];
  return <div className="site-shell"><header className="site-header"><Link href="#top" className="brand"><span className="brand-mark">Q</span><span>Mohd Zaheer Uddin</span></Link><nav className={`desktop-nav ${mobile ? "mobile-visible" : ""}`} aria-label="Primary navigation">{nav.map(([label,href]) => <Link key={label} href={href} className="nav-link" onClick={() => setMobile(false)}>{label}</Link>)}</nav><div className="header-actions"><ThemeToggle theme={theme} change={change}/><button className="mobile-menu-button" type="button" onClick={() => setMobile(v => !v)} aria-expanded={mobile} aria-label="Toggle navigation">{mobile ? <X size={20}/> : <List size={20}/>}</button></div></header>
  <main id="top"><section className="hero section-pad"><div className="hero-copy"><Reveal><p className="eyebrow"><span className="status-dot"/> CSIT undergraduate · ML &amp; Data Science</p></Reveal><Reveal delay={.08}><h1>I build practical machine learning projects and data-driven tools.</h1></Reveal><Reveal delay={.16}><p className="hero-description">Python-first, curious, and focused on turning concepts into useful things people can actually try.</p></Reveal><Reveal delay={.24}><div className="hero-actions"><a className="button button-primary" href="#work">See the work <ArrowDown size={17}/></a><button className="text-button" type="button" onClick={copyEmail}>{copied ? "Email copied" : "Copy email"} <PaperPlaneTilt size={16}/></button></div></Reveal><Reveal delay={.32}><div className="proof-row"><span>7 projects</span><span>Python + ML focus</span><span>Open to internships</span></div></Reveal></div><Reveal className="hero-art" delay={.16}><Terminal/><p className="hero-note">Try <b>help</b>, <b>projects</b>, <b>skills</b>, or <b>about</b>.</p></Reveal></section>
  <section id="work" className="section-pad section-block"><Reveal className="section-heading"><div><p className="eyebrow">Selected work</p><h2>Projects with a purpose.</h2></div><p>Small enough to explain. Real enough to show how I work.</p></Reveal><div className="work-layout"><div className="project-list">{projects.map((p,i) => <motion.button key={p[0]} className={`project-row ${active===i ? "active" : ""}`} onMouseEnter={() => setActive(i)} onFocus={() => setActive(i)} onClick={() => { setActive(i); tone("tap"); }} whileTap={{ scale: .985 }}><span className="project-number">{p[0]}</span><span className="project-name"><strong>{p[1]}</strong><small>{p[2]}</small></span><ArrowUpRight className="project-arrow" size={17}/></motion.button>)}</div><article className="project-detail surface"><div><div className="detail-top"><span className="eyebrow">{project[2]}</span><span>{project[0]}</span></div><h3>{project[1]}</h3><p>{project[3]}</p><div className="stack-row">{project[4].map(x => <span key={x}>{x}</span>)}</div></div><div className="detail-actions"><a className="button button-primary" href={project[5]} target="_blank" rel="noreferrer">Open project <ArrowUpRight size={16}/></a><a className="button button-secondary" href={project[6]} target="_blank" rel="noreferrer"><GithubLogo size={17}/> Source</a></div></article></div></section>
  <section id="about" className="section-pad section-block"><Reveal className="section-heading"><div><p className="eyebrow">About</p><h2>Curious, practical, still learning.</h2></div><p>Visible work, visible learning, steady improvement.</p></Reveal><div className="about-grid"><div className="about-copy"><p>I am a CSIT undergraduate focused on Python, machine learning, data analysis, and practical web development.</p><div className="about-facts"><span><Briefcase size={17}/> Open to internships</span><span><Code size={17}/> Python + ML</span><span><Sparkle size={17}/> Learning by building</span></div></div><Contributions/></div></section>
  <section id="journey" className="section-pad section-block"><Reveal className="section-heading"><div><p className="eyebrow">Journey</p><h2>From fundamentals to systems.</h2></div><p>Understand the basics, build projects, then make the projects better.</p></Reveal><div className="journey-grid">{[["01","Python foundations","Core syntax, OOP, files, data structures"],["02","ML experiments","Regression, classification, evaluation"],["03","Interactive apps","Turning models into usable tools"],["04","Better engineering","Responsive UI, deployment, accessibility"]].map(x => <Reveal key={x[0]}><article className="journey-item"><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article></Reveal>)}</div></section>
  <section id="skills" className="section-pad section-block"><Reveal className="section-heading"><div><p className="eyebrow">Skills</p><h2>The current toolkit.</h2></div><p>Tools I use today and continue improving through projects.</p></Reveal><div className="skills-grid">{skills.map(([name,desc],i) => <motion.article key={name} className="skill-card surface" whileHover={{ y:-4 }}><span className="skill-index">0{i+1}</span><strong>{name}</strong><span>{desc}</span></motion.article>)}</div></section>
  <section id="contact" className="section-pad section-block"><Reveal><div className="surface contact-card"><div><p className="eyebrow">Contact</p><h2>Let’s build something useful.</h2><p>Looking for an intern, collaborator, or someone who enjoys learning by building? I would love to hear from you.</p></div><div className="contact-actions"><button className="button button-primary" type="button" onClick={copyEmail}>{copied ? "Email copied" : "Copy email"} <PaperPlaneTilt size={17}/></button><a className="button button-secondary" href="https://www.linkedin.com" target="_blank" rel="noreferrer"><LinkedinLogo size={17}/> LinkedIn</a><a className="button button-secondary" href="https://github.com/SohailKhan0525" target="_blank" rel="noreferrer"><GithubLogo size={17}/> GitHub</a></div></div></Reveal></section></main><footer className="site-footer section-pad"><span>© 2026 Mohd Zaheer Uddin</span><span>Python mindset · shipped on Vercel</span></footer></div>;
}
